### ISSUE TITLE
trouble with the user model

### ISSUE THREAD

**Issue by libengebremedhin** [Ludis-ET/capstone-project#5]
class CustomUser(AbstractUser):
    is_author = models.BooleanField(default=False, verbose_name= "Make User an Author")
    is_manager = models.BooleanField(default=False, verbose_name= "Make User a Manager")

    class Meta:
        verbose_name = "Person"
        verbose_name_plural = "People"

**Comment by Ludis-ET** [comment]
CustomUser class:

This class is inheriting from AbstractUser, which is a built-in Django model class used for handling user authentication.
By subclassing AbstractUser, you're able to add custom fields and methods to the user model.
Custom fields:

is_author and is_manager are two boolean fields added to the custom user model.
They default to False, meaning by default a user is not considered an author or a manager.
These fields are used to determine whether a user has author or manager privileges in the application.
