### ISSUE TITLE
and also what is happening in the admin?

### ISSUE THREAD

**Issue by libengebremedhin** [Ludis-ET/capstone-project#6]
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser

# Register your models here.
@admin.register(CustomUser)
class UserAdmin(UserAdmin):
    list_display = ["is_author" ]
    form = CustomUserChangeForm
    add_form = CustomUserCreationForm
    fieldsets = (
        (None, {'fields': ('username', 'password', 'is_author', 'is_manager')}),
        ('Permissions', {'fields': ('is_active',)}),
    )
    add_fieldsets = (
        ("Base User", {
            'classes': ('wide',),
            'fields': ('username', 'password1', 'password2', 'is_author', 'is_manager', 'is_active'),
        }),
    )

**Comment by Ludis-ET** [comment]
CustomUserChangeForm and CustomUserCreationForm:

These are custom forms used for changing and creating user accounts, respectively.
They are based on existing forms provided by Django called UserChangeForm and UserCreationForm.
